### ISSUE TITLE
Support for Apple Silicon using Homebrew installed Python

### ISSUE THREAD

**Issue by sunilshah** [cvxgrp/cvxmarkowitz#183]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Ex. I'm always frustrated when [...]

I use Homebrew installed python (3.11.7 currently) pip3 (24.0).  I use pip3 installed  cvxpy(1.4.2) , open source cvxpy solvers along with jupyterlab (4.1.1).  I use both arm64 and i386 (Rosetta2) versions because some codes run faster in one or the other. I have been running a modified version of cvxportfolio in Jupyterlab / notebook for  a while. 

Poetry does not seem to work in this environment.  See unresolved issues on Github (install.python-poetry.org)  for over a year : [Poetry environment Issue #71](https://github.com/python-poetry/install.python-poetry.org/issues/71)
[Poetrey Installer Issue 133](https://github.com/python-poetry/install.python-poetry.org/pull/133)

I want to evaluate cvxmarkowitz but seems like it assumes use of poetry for the install.  Is that true?  If I use pip3 to install all the required packages is there a way to make it work on Apple Silicon / Homebrew?  

**Describe the solution you'd like**

It would be nice if there was a working version of cvxmarkowitz and  examples that (1) works on Apple Silicon with homebrew installed python3 and other packages / libraries using pip3.  (2) open-source non-proprietary solvers for cvxpy (MOSEK trial license not needed).   

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions
or features you've considered.

**Additional context**

**Comment by tschm** [comment]
Thank you for your comment

* You can clone the repo and use poetry (see https://python-poetry.org) and then `make install` to construct the virtual environment used and expected by cvxmarkowitz

* The correct link to the poetry issue is https://github.com/python-poetry/install.python-poetry.org/issues/71

* I would recommend using pyenv to manage your local Python installations. Do not rely on homebrew for that job. In those environments you can actually pip install poetry (although poetry people would not recommend that).

It's also a bit too early to evaluate cvxmarkowitz. It's a bit too early at this stage. We have not yet published a version of it on pypi and once we have you can simply run "pip install cvxmarkowitz".

**Comment by sunilshah** [comment]
Thanks @tschm!

I will check out use of `pyenv` with my homebrew installs for separation.   Once that works, I will try poetry per the documentation.  However, the sheer number of open issues in poetry repo on GitHub makes me wonder if it will be robust.

**Comment by sunilshah** [comment]
Hi @tschm 

I did manage to use the built-in venv to create environments with different versions of installed homebrew python and tested that they work in Jupyter lab kernels as expected.  

Next, I downloaded `cvxgrp/cvxmarkowitz` and ran `make install` per your instructions in `README.md`.  That seemed to work fine. `make test' worked.  
However, there is no `make kernel` entry in your Makefile.  I assumed you wanted to build Jupyter so I built it using `poetry run pip3 install jupyterlab`, `poetry run Jupyter lab build`.  What kernel did you want to build?  

Separately, `make coverage` reports missing `cvx/markowitz/portfolios/soft_risk.py         28     28     0%   14-67`.

Trying to run examples:  

`$poetry run python backtest.py `

`Traceback (most recent call last):
  File "/Users/sunilshah/Library/Mobile Documents/com~apple~CloudDocs/Python/cvxmarkowitz-main/experiments/backtest.py", line 11, in <module>
    from cvx.simulator.builder import builder
ImportError: cannot import name 'builder' from 'cvx.simulator.builder' (/Users/sunilshah/Library/Caches/pypoetry/virtualenvs/cvxmarkowitz-glLIiM4z-py3.11/lib/python3.11/site-packages/cvx/simulator/builder.py)`

Suggestions?

**Comment by tschm** [comment]
@sunilshah. Ok, I should add the make kernel to the Makefile. However, it's not really needed as make jupyter installs jupyterlab in the same python environment. Maybe my documentation is a bit out of sync here... You should use the python3 standard kernel if jupyter and cvxmarkowitz are served from the same environment. The backtest.py is a problem. I need to sync with the cvx.simulator package...

**Comment by sunilshah** [comment]
Thanks @tschm
