### ISSUE TITLE
Serialize problems

### ISSUE THREAD

**Issue by tschm** [cvxgrp/cvxmarkowitz#88]

**Comment by tschm** [comment]
@phschiele: What's the latest state on serialization of cvxpy problems? Is it safe to use for now pickle? I remember there was an alternative to pickle that's more powerful but I forgot the name

**Comment by phschiele** [comment]
@tschm Maybe you mean `dill`? Right now, serialization is not officially supported.
It should work for most simple/unsolved problems, though.
The best workaround so far is described here:
https://github.com/cvxpy/cvxpy/issues/1438#issuecomment-879081133
